<h1><?php echo ucfirst($this->titre); ?></h1>
<fieldset>
    <legend>Listing</legend>
</fieldset>

<?php
if (count($this->fournisseurs)):
    ?>
    <a href="/fournisseur/ajouter">
        <i class="icon-plus-sign"></i> Ajouter
    </a>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>id</th>
                <th>fournisseur</th>
                <th>Modifier</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->fournisseurs as $item): ?>
                <tr>
                    <td><?php echo $item->ID_FOURNISSEUR; ?></td>
                    <td><?php echo $item->VALEUR; ?></td>
                    <td>
                        <a href="/fournisseur/editer/idFournisseur/<?php echo $item->ID_FOURNISSEUR; ?>">
                            <i class="icon-edit"></i>
                        </a>
                    </td>
                </tr>

            <?php endforeach; ?>
        </tbody>
    </table>

    <?php
/*
  echo $this->paginationControl(
  $this->resultatPagination,
  Zend_Registry::get('define')->pagination->typeDeDefilement,
  Zend_Registry::get('define')->pagination->pageDeRendu,
  $this->formData
  );
 */
endif;
?>